### PR TITLE
Exit 1 if Pytest does not exit 0

### PR DESCRIPTION
**Pull request by kieronellis**

### CODE REVIEW

**Comment by kieronellis** [comment]
@jayamanikharyono

**Comment by jayamanikharyono** [comment]
Merged @kieronellis, Thank you for your Contribution

**Comment by jayamanikharyono** [comment]
Thank you for your Contribution

**Comment by kieronellis** [comment]
@jayamanikharyono could you create a new release?

**Comment by jayamanikharyono** [comment]
This is the release ya https://github.com/jayamanikharyono/airflow-dag-action/releases/tag/v2.1 @kieronellis

**Pull request merged**
